// composables/system.js

export const useCouriers = () => {
  const couriers = {
    'DAZI DOG.': { label: 'DAZI DOG.', selectable: true },
    'DAZI': { label: 'DAZI', selectable: true },
    'EX.SH.DAZIO': { label: 'EX.SH.DAZIO', selectable: true },
    'DEI ROSSI SH': { label: 'DEI ROSSI SH', selectable: true },
    'DHL': { label: 'DHL', selectable: true },
    'DHL 2^SHIP': { label: 'DHL 2^SHIP', selectable: true },
    'DHL 1^ SHIP': { label: 'DHL 1^ SHIP', selectable: true },
    'DHL 2^ SHIP': { label: 'DHL 2^ SHIP', selectable: true },
    'DHL BUSTA': { label: 'DHL BUSTA', selectable: true },
    'DHL DAZI': { label: 'DHL DAZI', selectable: true },
    'DHL DOC': { label: 'DHL DOC', selectable: true },
    'DHL DOCUM.': { label: 'DHL DOCUM.', selectable: true },
    'DHL DOGANA': { label: 'DHL DOGANA', selectable: true },
    'DHL FLYER': { label: 'DHL FLYER', selectable: true },
    'DHL FLYER R.': { label: 'DHL FLYER R.', selectable: true },
    'DHL GIFT': { label: 'DHL GIFT', selectable: true },
    'DHL OMAGGIO': { label: 'DHL OMAGGIO', selectable: true },
    'DHL PROFORMA': { label: 'DHL PROFORMA', selectable: true },
    'DHL REINOLTR': { label: 'DHL REINOLTR', selectable: true },
    'DHL REPL': { label: 'DHL REPL', selectable: true },
    'DHL REPL.': { label: 'DHL REPL.', selectable: true },
    'DHL RIENTRO': { label: 'DHL RIENTRO', selectable: true },
    'DHL RIMP': { label: 'DHL RIMP', selectable: true },
    'DHL RIMP.': { label: 'DHL RIMP.', selectable: true },
    'DHL RIT.': { label: 'DHL RIT.', selectable: true },
    'DHL RITORNO': { label: 'DHL RITORNO', selectable: true },
    'DHL SPECCHIO': { label: 'DHL SPECCHIO', selectable: true },
    'DHL-GIFT': { label: 'DHL-GIFT', selectable: true },
    'DHL-OMAGGIO': { label: 'DHL-OMAGGIO', selectable: true },
    'DHL-SAMPLE': { label: 'DHL-SAMPLE', selectable: true },
    'DIFF PESO': { label: 'DIFF PESO', selectable: true },
    'DIFF.P.T.': { label: 'DIFF.P.T.', selectable: true },
    'DIFF.P.TASS': { label: 'DIFF.P.TASS', selectable: true },
    'DIFF.P.TASS.': { label: 'DIFF.P.TASS.', selectable: true },
    'DIFF.PESO': { label: 'DIFF.PESO', selectable: true },
    'DIFF.PESO T.': { label: 'DIFF.PESO T.', selectable: true },
    'DII.PESO': { label: 'DII.PESO', selectable: true },
    'DOCS': { label: 'DOCS', selectable: true },
    'DUTY': { label: 'DUTY', selectable: true },
    'EX  DIFF PES': { label: 'EX  DIFF PES', selectable: true },
    'EX CONS FZ': { label: 'EX CONS FZ', selectable: true },
    'EX CORR INDEX DAZI': { label: 'EX CORR INDEX DAZI', selectable: true },
    'EX DAZIO': { label: 'EX DAZIO', selectable: true },
    'EX DIFF PE': { label: 'EX DIFF PE', selectable: true },
    'EX DIFF PESO': { label: 'EX DIFF PESO', selectable: true },
    'EX DUTY': { label: 'EX DUTY', selectable: true },
    'EX RIEN MER': { label: 'EX RIEN MER', selectable: true },
    'EX S-GIFT': { label: 'EX S-GIFT', selectable: true },
    'EX SH DIF PE': { label: 'EX SH DIF PE', selectable: true },
    'EX SH DIFF PE': { label: 'EX SH DIFF PE', selectable: true },
    'EX SH domici': { label: 'EX SH domici', selectable: true },
    'EX SH DUTY': { label: 'EX SH DUTY', selectable: true },
    'EX SH FZONA': { label: 'EX SH FZONA', selectable: true },
    'EX Shcon sab': { label: 'EX Shcon sab', selectable: true },
    'EX SHIP': { label: 'EX SHIP', selectable: true },
    'EXP  2^ CONS': { label: 'EXP  2^ CONS', selectable: true },
    'EXP  SH. DPT': { label: 'EXP  SH. DPT', selectable: true },
    'EXP C.F.Z.': { label: 'EXP C.F.Z.', selectable: true },
    'EXP COR.IND': { label: 'EXP COR.IND', selectable: true },
    'EXP CORR.IND': { label: 'EXP CORR.IND', selectable: true },
    'EXP CORR/IND': { label: 'EXP CORR/IND', selectable: true },
    'EXP DAZI': { label: 'EXP DAZI', selectable: true },
    'EXP DAZIO': { label: 'EXP DAZIO', selectable: true },
    'EXP DOGANA': { label: 'EXP DOGANA', selectable: true },
    'EXP RIENTRO': { label: 'EXP RIENTRO', selectable: true },
    'EXP RISP.': { label: 'EXP RISP.', selectable: true },
    'EXP S 2^ R': { label: 'EXP S 2^ R', selectable: true },
    'EXP S BUSTA': { label: 'EXP S BUSTA', selectable: true },
    'EXP S DAZI': { label: 'EXP S DAZI', selectable: true },
    'EXP S GIFT': { label: 'EXP S GIFT', selectable: true },
    'EXP S PICKUP': { label: 'EXP S PICKUP', selectable: true },
    'EXP S-GIFT': { label: 'EXP S-GIFT', selectable: true },
    'EXP S. BUSTA': { label: 'EXP S. BUSTA', selectable: true },
    'EXP S. GIFT': { label: 'EXP S. GIFT', selectable: true },
    'EXP S.sample': { label: 'EXP S.sample', selectable: true },
    'EXP SH.': { label: 'EXP SH.', selectable: true },
    'EXP SH. GIFT': { label: 'EXP SH. GIFT', selectable: true },
    'EXP SH.busta': { label: 'EXP SH.busta', selectable: true },
    'EXP SH.CFZ': { label: 'EXP SH.CFZ', selectable: true },
    'EXP SH.DAZI': { label: 'EXP SH.DAZI', selectable: true },
    'EXP SH.DIFF': { label: 'EXP SH.DIFF', selectable: true },
    'EXP SH.DPT': { label: 'EXP SH.DPT', selectable: true },
    'EXP SHI': { label: 'EXP SHI', selectable: true },
    'EXP SHI dazi': { label: 'EXP SHI dazi', selectable: true },
    'EXP SHIP': { label: 'EXP SHIP', selectable: true },
    'EXP SHIP 1^': { label: 'EXP SHIP 1^', selectable: true },
    'EXP SHIP 1^S': { label: 'EXP SHIP 1^S', selectable: true },
    'EXP SHIP 1SH': { label: 'EXP SHIP 1SH', selectable: true },
    'EXP SHIP 2': { label: 'EXP SHIP 2', selectable: true },
    'EXP SHIP 2 ^': { label: 'EXP SHIP 2 ^', selectable: true },
    'EXP SHIP 2^': { label: 'EXP SHIP 2^', selectable: true },
    'EXP SHIP 2^S': { label: 'EXP SHIP 2^S', selectable: true },
    'EXP SHIP 2/3': { label: 'EXP SHIP 2/3', selectable: true },
    'EXP SHIP 2SH': { label: 'EXP SHIP 2SH', selectable: true },
    'EXP SHIP 3^': { label: 'EXP SHIP 3^', selectable: true },
    'EXP SHIP 3^S': { label: 'EXP SHIP 3^S', selectable: true },
    'EXP SHIP 3SH': { label: 'EXP SHIP 3SH', selectable: true },
    'EXP SHIP BUS': { label: 'EXP SHIP BUS', selectable: true },
    'EXP SHIP CFZ': { label: 'EXP SHIP CFZ', selectable: true },
    'EXP SHIP COR': { label: 'EXP SHIP COR', selectable: true },
    'EXP SHIP DAZ': { label: 'EXP SHIP DAZ', selectable: true },
    'EXP SHIP DIF': { label: 'EXP SHIP DIF', selectable: true },
    'EXP SHIP DOC': { label: 'EXP SHIP DOC', selectable: true },
    'EXP SHIP DOG': { label: 'EXP SHIP DOG', selectable: true },
    'EXP SHIP DPT': { label: 'EXP SHIP DPT', selectable: true },
    'EXP SHIP GIF': { label: 'EXP SHIP GIF', selectable: true },
    'EXP SHIP MAG': { label: 'EXP SHIP MAG', selectable: true },
    'EXP SHIP MEX': { label: 'EXP SHIP MEX', selectable: true },
    'EXP SHIP nmg': { label: 'EXP SHIP nmg', selectable: true },
    'EXP SHIP R': { label: 'EXP SHIP R', selectable: true },
    'EXP SHIP R.': { label: 'EXP SHIP R.', selectable: true },
    'EXP SHIP R/G': { label: 'EXP SHIP R/G', selectable: true },
    'EXP SHIP REP': { label: 'EXP SHIP REP', selectable: true },
    'EXP SHIP RIP': { label: 'EXP SHIP RIP', selectable: true },
    'EXP SHIP RIS': { label: 'EXP SHIP RIS', selectable: true },
    'EXP SHIP TRA': { label: 'EXP SHIP TRA', selectable: true },
    'EXP SHIP USA': { label: 'EXP SHIP USA', selectable: true },
    'EXP SHIP/1': { label: 'EXP SHIP/1', selectable: true },
    'EXP SHIP/2': { label: 'EXP SHIP/2', selectable: true },
    'EXP SHIPGIFT': { label: 'EXP SHIPGIFT', selectable: true },
    'EXP SHP': { label: 'EXP SHP', selectable: true },
    'EXP SHP CFZ': { label: 'EXP SHP CFZ', selectable: true },
    'EXP SJHIP': { label: 'EXP SJHIP', selectable: true },
    'EXP SPE RIEN': { label: 'EXP SPE RIEN', selectable: true },
    'EXP.S.Busta*': { label: 'EXP.S.Busta*', selectable: true },
    'EXP.S.pickup': { label: 'EXP.S.pickup', selectable: true },
    'EXP.S.sample': { label: 'EXP.S.sample', selectable: true },
    'EXPOTRANS': { label: 'EXPOTRANS', selectable: true },
    'EXPRESS SHIP': { label: 'EXPRESS SHIP', selectable: true },
    'EXPS - GIFT': { label: 'EXPS - GIFT', selectable: true },
    'EXPS BUSTA': { label: 'EXPS BUSTA', selectable: true },
    'EXPS BUSTA D': { label: 'EXPS BUSTA D', selectable: true },
    'EXPS DOCS': { label: 'EXPS DOCS', selectable: true },
    'EXPS GIFT': { label: 'EXPS GIFT', selectable: true },
    'EXPS OMAGGIO': { label: 'EXPS OMAGGIO', selectable: true },
    'EXPS R': { label: 'EXPS R', selectable: true },
    'EXPS RIP.': { label: 'EXPS RIP.', selectable: true },
    'EXPS SAMPLES': { label: 'EXPS SAMPLES', selectable: true },
    'EXPS SHIP': { label: 'EXPS SHIP', selectable: true },
    'EXPS-GIFT': { label: 'EXPS-GIFT', selectable: true },
    'EXPSHIP 1^S': { label: 'EXPSHIP 1^S', selectable: true },
    'EXPSHIP 2 SH': { label: 'EXPSHIP 2 SH', selectable: true },
    'EXPSHIP 2^': { label: 'EXPSHIP 2^', selectable: true },
    'EXPSHIP 2^S': { label: 'EXPSHIP 2^S', selectable: true },
    'EXPSHIP DOCS': { label: 'EXPSHIP DOCS', selectable: true },
    'EXPSHIP GIFT': { label: 'EXPSHIP GIFT', selectable: true },
    'EXPSHIP R': { label: 'EXPSHIP R', selectable: true },
    'EXPSHIP REPL': { label: 'EXPSHIP REPL', selectable: true },
    'EXPSHIP-GIFT': { label: 'EXPSHIP-GIFT', selectable: true },
    'EXS RIORDINO': { label: 'EXS RIORDINO', selectable: true },
    'FEDEX': { label: 'FEDEX', selectable: true },
    'FEDEX RIT.': { label: 'FEDEX RIT.', selectable: true },
    'franco TRK': { label: 'franco TRK', selectable: true },
    'FUORI ZONA': { label: 'FUORI ZONA', selectable: true },
    'GENERAL CARG': { label: 'GENERAL CARG', selectable: true },
    'ITALIANSPED': { label: 'ITALIANSPED', selectable: true },
    'MAG EXP SHIP': { label: 'MAG EXP SHIP', selectable: true },
    'MAGAZZINO': { label: 'MAGAZZINO', selectable: true },
    'MEDVEDGROUP': { label: 'MEDVEDGROUP', selectable: true },
    'MEDVEDGROUPR': { label: 'MEDVEDGROUPR', selectable: true },
    'NEW V. BUSTA': { label: 'NEW V. BUSTA', selectable: true },
    'NEW VE.DOCS': { label: 'NEW VE.DOCS', selectable: true },
    'NEW VENICE': { label: 'NEW VENICE', selectable: true },
    'NEW VENICE R': { label: 'NEW VENICE R', selectable: true },
    'NEW VENICE1^': { label: 'NEW VENICE1^', selectable: true },
    'NEW VENICE2^': { label: 'NEW VENICE2^', selectable: true },
    'PERS. RIMP.': { label: 'PERS. RIMP.', selectable: true },
    'PERSONALE': { label: 'PERSONALE', selectable: true },
    'PERSONALE 1^': { label: 'PERSONALE 1^', selectable: true },
    'PERSONALE R': { label: 'PERSONALE R', selectable: true },
    'PERSONALE R.': { label: 'PERSONALE R.', selectable: true },
    'PICK UP': { label: 'PICK UP', selectable: true },
    'PICK UP EXP': { label: 'PICK UP EXP', selectable: true },
    'PICK UP EXPS': { label: 'PICK UP EXPS', selectable: true },
    'PICK UP PERS': { label: 'PICK UP PERS', selectable: true },
    'PICKUP': { label: 'PICKUP', selectable: true },
    'POSTE A/R': { label: 'POSTE A/R', selectable: true },
    'PROVA CONS.': { label: 'PROVA CONS.', selectable: true },
    'RIENTRO': { label: 'RIENTRO', selectable: true },
    'RIENTRO DHL': { label: 'RIENTRO DHL', selectable: true },
    'RIENTRO MERC': { label: 'RIENTRO MERC', selectable: true },
    'RIT. FEDEX': { label: 'RIT. FEDEX', selectable: true },
    'RITIRO': { label: 'RITIRO', selectable: true },
    'STEP': { label: 'STEP', selectable: true },
    'TECNOFREIGHT': { label: 'TECNOFREIGHT', selectable: true },
    'TR.DEI ROSSI': { label: 'TR.DEI ROSSI', selectable: true },
    'UPS': { label: 'UPS', selectable: true },
    'UPS 1^ SHIP': { label: 'UPS 1^ SHIP', selectable: true },
    'UPS 2^ SHIP': { label: 'UPS 2^ SHIP', selectable: true },
    'UPS ENVELOPE': { label: 'UPS ENVELOPE', selectable: true },
    'UPS EXP TUBE': { label: 'UPS EXP TUBE', selectable: true },
    'UPS R.': { label: 'UPS R.', selectable: true },
    'UPS REPL': { label: 'UPS REPL', selectable: true },
    'UPS REPL.': { label: 'UPS REPL.', selectable: true },
    'UPS RIENTRO': { label: 'UPS RIENTRO', selectable: true },
    'UPS RIMP.': { label: 'UPS RIMP.', selectable: true },
    'UPS-REPL.': { label: 'UPS-REPL.', selectable: true },
    'VARDANIAN I.': { label: 'VARDANIAN I.', selectable: true },
    'VISITA DOG.': { label: 'VISITA DOG.', selectable: true }
  }

  // Array solo dei corrieri selezionabili per le select
  const selectableCouriers = Object.entries(couriers)
    .filter(([key, value]) => value.selectable)
    .map(([key]) => key)
    .sort()

  // Array di tutti i corrieri (anche non selezionabili)
  const allCouriers = Object.keys(couriers).sort()

  // Funzione per verificare se un corriere esiste
  const isCourier = (value) => {
    return couriers.hasOwnProperty(value)
  }

  // Funzione per verificare se un corriere è selezionabile
  const isSelectable = (value) => {
    return couriers[value]?.selectable === true
  }

  // Ottieni label di un corriere
  const getCourierLabel = (value) => {
    return couriers[value]?.label || value
  }

  return {
    couriers,
    selectableCouriers,
    allCouriers,
    isCourier,
    isSelectable,
    getCourierLabel
  }
}